#!/bin/bash
. /opt/env.sh

convert -bordercolor white -border 16x16 input.tiff binput.tiff

SIZE=`identify binput.tiff  |cut -d' ' -f3`
PIXELS=`echo $SIZE | tr 'x' '*'|bc`
#compile
vsim -c -do compile.do

rm -f *.mono sim.*out*

convert binput.tiff sim.mono
#mv sim-0.mono sim.mono

# Raw to ascii bin
cat sim.mono | hexdump -v -e '/1 "%02X\n"'  | ./bin2b.py > sim.dat

# Pipe
vsim -c -GWIDTH=160 -GHEIGHT=160 -do sim_batch.do

#################################
# From ascii to bin
cat sim.out | ./hex2b.py  > sim.mono

rm -f sim.tiff
# From bin to tiff
convert -size $SIZE  sim.mono -size $SIZE  sim.tiff

# Offset by +2+2
convert sim.tiff -background white -chop 2x2 -gravity southeast -splice 2x2 _sim.tiff
mv _sim.tiff sim.tiff
convert sim.tiff -background white -chop 2x2 -gravity southeast -splice 2x2 _sim.tiff
mv _sim.tiff sim.tiff
convert sim.tiff -background white -chop 2x2 -gravity southeast -splice 2x2 _sim.tiff
mv _sim.tiff sim.tiff
convert sim.tiff -background white -chop 2x2 -gravity southeast -splice 2x2 _sim.tiff
mv _sim.tiff sim.tiff

rm -f sim.mono

# Back again to mono
convert sim.tiff sim.mono
#mv sim-0.mono sim.mono
cp sim.tiff sim.out.tiff
# Cut relevant pixels
head -c $PIXELS sim.mono  > _sim.mono
mv _sim.mono sim.mono

md5sum sim.mono > sim.md5sum

rm -f *.mono

####################################
# Generate reference
convert binput.tiff  -morphology Dilate Octagon:2 -morphology Dilate Octagon:2 -morphology Dilate Octagon:2 -morphology Dilate Octagon:2 sim.tiff
#convert binput.tiff  -morphology Erode Square:2 sim.tiff

# To mono
convert sim.tiff sim.mono
#mv sim-0.mono sim.mono

# Cut relevant pixels
head -c $PIXELS sim.mono  > _sim.mono
mv _sim.mono sim.mono

md5sum --check sim.md5sum


# Show
#qiv -W 1000 sim.out.tiff sim.ref.tiff 
