# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created: Sun Jul 22 14:19:07 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.enable = QtGui.QListWidget(self.centralwidget)
        self.enable.setGeometry(QtCore.QRect(60, 40, 221, 391))
        self.enable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.enable.setObjectName(_fromUtf8("enable"))
        self.pushButton_exit = QtGui.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(670, 50, 95, 31))
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 30, 281, 231))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.slides = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.slides.setMargin(0)
        self.slides.setObjectName(_fromUtf8("slides"))
        self.morph_th = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th.setMinimum(1)
        self.morph_th.setMaximum(21)
        self.morph_th.setPageStep(4)
        self.morph_th.setOrientation(QtCore.Qt.Vertical)
        self.morph_th.setInvertedAppearance(False)
        self.morph_th.setInvertedControls(False)
        self.morph_th.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th.setTickInterval(1)
        self.morph_th.setObjectName(_fromUtf8("morph_th"))
        self.slides.addWidget(self.morph_th)
        self.morph_th_2 = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th_2.setMinimum(1)
        self.morph_th_2.setMaximum(21)
        self.morph_th_2.setPageStep(4)
        self.morph_th_2.setOrientation(QtCore.Qt.Vertical)
        self.morph_th_2.setInvertedAppearance(False)
        self.morph_th_2.setInvertedControls(False)
        self.morph_th_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th_2.setTickInterval(1)
        self.morph_th_2.setObjectName(_fromUtf8("morph_th_2"))
        self.slides.addWidget(self.morph_th_2)
        self.morph_th_3 = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th_3.setMinimum(1)
        self.morph_th_3.setMaximum(21)
        self.morph_th_3.setPageStep(4)
        self.morph_th_3.setOrientation(QtCore.Qt.Vertical)
        self.morph_th_3.setInvertedAppearance(False)
        self.morph_th_3.setInvertedControls(False)
        self.morph_th_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th_3.setTickInterval(1)
        self.morph_th_3.setObjectName(_fromUtf8("morph_th_3"))
        self.slides.addWidget(self.morph_th_3)
        self.morph_th_4 = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th_4.setMinimum(1)
        self.morph_th_4.setMaximum(21)
        self.morph_th_4.setPageStep(4)
        self.morph_th_4.setOrientation(QtCore.Qt.Vertical)
        self.morph_th_4.setInvertedAppearance(False)
        self.morph_th_4.setInvertedControls(False)
        self.morph_th_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th_4.setTickInterval(1)
        self.morph_th_4.setObjectName(_fromUtf8("morph_th_4"))
        self.slides.addWidget(self.morph_th_4)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(340, 280, 321, 261))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout.addWidget(self.radioButton_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.motion_p01 = QtGui.QSlider(self.horizontalLayoutWidget_3)
        self.motion_p01.setMinimum(0)
        self.motion_p01.setMaximum(65535)
        self.motion_p01.setPageStep(127)
        self.motion_p01.setOrientation(QtCore.Qt.Vertical)
        self.motion_p01.setInvertedAppearance(False)
        self.motion_p01.setInvertedControls(False)
        self.motion_p01.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p01.setTickInterval(1000)
        self.motion_p01.setObjectName(_fromUtf8("motion_p01"))
        self.horizontalLayout.addWidget(self.motion_p01)
        self.motion_p23 = QtGui.QSlider(self.horizontalLayoutWidget_3)
        self.motion_p23.setMinimum(0)
        self.motion_p23.setMaximum(65535)
        self.motion_p23.setPageStep(127)
        self.motion_p23.setOrientation(QtCore.Qt.Vertical)
        self.motion_p23.setInvertedAppearance(False)
        self.motion_p23.setInvertedControls(False)
        self.motion_p23.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p23.setTickInterval(1000)
        self.motion_p23.setObjectName(_fromUtf8("motion_p23"))
        self.horizontalLayout.addWidget(self.motion_p23)
        self.motion_p4 = QtGui.QSlider(self.horizontalLayoutWidget_3)
        self.motion_p4.setMinimum(0)
        self.motion_p4.setMaximum(7)
        self.motion_p4.setPageStep(1)
        self.motion_p4.setOrientation(QtCore.Qt.Vertical)
        self.motion_p4.setInvertedAppearance(False)
        self.motion_p4.setInvertedControls(False)
        self.motion_p4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p4.setTickInterval(1)
        self.motion_p4.setObjectName(_fromUtf8("motion_p4"))
        self.horizontalLayout.addWidget(self.motion_p4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "DETECT", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "VAR", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "MEM", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "IMG", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "DELTA", None, QtGui.QApplication.UnicodeUTF8))

