# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created: Sun Jul 22 19:59:19 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(740, 608)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.enable = QtGui.QListWidget(self.centralwidget)
        self.enable.setGeometry(QtCore.QRect(10, 20, 251, 511))
        self.enable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.enable.setObjectName(_fromUtf8("enable"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 20, 211, 251))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 211, 231))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.slides = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.slides.setMargin(0)
        self.slides.setObjectName(_fromUtf8("slides"))
        self.morph_th = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th.setMinimum(1)
        self.morph_th.setMaximum(21)
        self.morph_th.setPageStep(4)
        self.morph_th.setOrientation(QtCore.Qt.Vertical)
        self.morph_th.setInvertedAppearance(False)
        self.morph_th.setInvertedControls(False)
        self.morph_th.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th.setTickInterval(1)
        self.morph_th.setObjectName(_fromUtf8("morph_th"))
        self.slides.addWidget(self.morph_th)
        self.morph_th_2 = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th_2.setMinimum(1)
        self.morph_th_2.setMaximum(21)
        self.morph_th_2.setPageStep(4)
        self.morph_th_2.setOrientation(QtCore.Qt.Vertical)
        self.morph_th_2.setInvertedAppearance(False)
        self.morph_th_2.setInvertedControls(False)
        self.morph_th_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th_2.setTickInterval(1)
        self.morph_th_2.setObjectName(_fromUtf8("morph_th_2"))
        self.slides.addWidget(self.morph_th_2)
        self.morph_th_3 = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th_3.setMinimum(1)
        self.morph_th_3.setMaximum(21)
        self.morph_th_3.setPageStep(4)
        self.morph_th_3.setOrientation(QtCore.Qt.Vertical)
        self.morph_th_3.setInvertedAppearance(False)
        self.morph_th_3.setInvertedControls(False)
        self.morph_th_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th_3.setTickInterval(1)
        self.morph_th_3.setObjectName(_fromUtf8("morph_th_3"))
        self.slides.addWidget(self.morph_th_3)
        self.morph_th_4 = QtGui.QSlider(self.horizontalLayoutWidget)
        self.morph_th_4.setMinimum(1)
        self.morph_th_4.setMaximum(21)
        self.morph_th_4.setPageStep(4)
        self.morph_th_4.setOrientation(QtCore.Qt.Vertical)
        self.morph_th_4.setInvertedAppearance(False)
        self.morph_th_4.setInvertedControls(False)
        self.morph_th_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.morph_th_4.setTickInterval(1)
        self.morph_th_4.setObjectName(_fromUtf8("morph_th_4"))
        self.slides.addWidget(self.morph_th_4)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 280, 231, 251))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 231, 231))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout.addWidget(self.radioButton_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.motion_p23 = QtGui.QSlider(self.horizontalLayoutWidget_4)
        self.motion_p23.setMinimum(0)
        self.motion_p23.setMaximum(65535)
        self.motion_p23.setSingleStep(1)
        self.motion_p23.setPageStep(256)
        self.motion_p23.setOrientation(QtCore.Qt.Vertical)
        self.motion_p23.setInvertedAppearance(False)
        self.motion_p23.setInvertedControls(False)
        self.motion_p23.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p23.setTickInterval(1000)
        self.motion_p23.setObjectName(_fromUtf8("motion_p23"))
        self.horizontalLayout.addWidget(self.motion_p23)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.motion_p4 = QtGui.QSlider(self.horizontalLayoutWidget_4)
        self.motion_p4.setMinimum(0)
        self.motion_p4.setMaximum(7)
        self.motion_p4.setPageStep(1)
        self.motion_p4.setOrientation(QtCore.Qt.Vertical)
        self.motion_p4.setInvertedAppearance(False)
        self.motion_p4.setInvertedControls(False)
        self.motion_p4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p4.setTickInterval(1)
        self.motion_p4.setObjectName(_fromUtf8("motion_p4"))
        self.horizontalLayout_3.addWidget(self.motion_p4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 2, 1, 1)
        self.motion_p01 = QtGui.QSlider(self.horizontalLayoutWidget_4)
        self.motion_p01.setMinimum(0)
        self.motion_p01.setMaximum(65535)
        self.motion_p01.setPageStep(256)
        self.motion_p01.setOrientation(QtCore.Qt.Vertical)
        self.motion_p01.setInvertedAppearance(False)
        self.motion_p01.setInvertedControls(False)
        self.motion_p01.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p01.setTickInterval(1000)
        self.motion_p01.setObjectName(_fromUtf8("motion_p01"))
        self.gridLayout.addWidget(self.motion_p01, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(560, 30, 160, 491))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setMargin(10)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_exit = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_exit.setFlat(False)
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))
        self.verticalLayout_2.addWidget(self.pushButton_exit)
        self.preset_1 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.preset_1.setObjectName(_fromUtf8("preset_1"))
        self.verticalLayout_2.addWidget(self.preset_1)
        self.preset_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.preset_2.setObjectName(_fromUtf8("preset_2"))
        self.verticalLayout_2.addWidget(self.preset_2)
        self.preset_3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.preset_3.setObjectName(_fromUtf8("preset_3"))
        self.verticalLayout_2.addWidget(self.preset_3)
        self.preset_4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.preset_4.setObjectName(_fromUtf8("preset_4"))
        self.verticalLayout_2.addWidget(self.preset_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Morph threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Motion", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "DETECT", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "VAR", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "MEM", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "IMG", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "DELTA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "vmax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "vmin", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exit.setText(QtGui.QApplication.translate("MainWindow", "EXIT", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_1.setText(QtGui.QApplication.translate("MainWindow", "Preset 1", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_2.setText(QtGui.QApplication.translate("MainWindow", "Preset 2", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_3.setText(QtGui.QApplication.translate("MainWindow", "Preset 3", None, QtGui.QApplication.UnicodeUTF8))
        self.preset_4.setText(QtGui.QApplication.translate("MainWindow", "Preset 4", None, QtGui.QApplication.UnicodeUTF8))

