# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motion.ui'
#
# Created: Mon Sep 17 22:15:18 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MotionBox(object):
    def setupUi(self, MotionBox):
        MotionBox.setObjectName(_fromUtf8("MotionBox"))
        MotionBox.resize(388, 255)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MotionBox.sizePolicy().hasHeightForWidth())
        MotionBox.setSizePolicy(sizePolicy)
        MotionBox.setMinimumSize(QtCore.QSize(388, 0))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(MotionBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 387, 231))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout.addWidget(self.radioButton_5)
        self.lock = QtGui.QCheckBox(self.horizontalLayoutWidget_4)
        self.lock.setObjectName(_fromUtf8("lock"))
        self.verticalLayout.addWidget(self.lock)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.motion_p23 = QtGui.QSlider(self.horizontalLayoutWidget_4)
        self.motion_p23.setMinimum(0)
        self.motion_p23.setMaximum(65535)
        self.motion_p23.setSingleStep(1)
        self.motion_p23.setPageStep(256)
        self.motion_p23.setOrientation(QtCore.Qt.Vertical)
        self.motion_p23.setInvertedAppearance(False)
        self.motion_p23.setInvertedControls(False)
        self.motion_p23.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p23.setTickInterval(1000)
        self.motion_p23.setObjectName(_fromUtf8("motion_p23"))
        self.horizontalLayout.addWidget(self.motion_p23)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.motion_p4 = QtGui.QSlider(self.horizontalLayoutWidget_4)
        self.motion_p4.setMinimum(0)
        self.motion_p4.setMaximum(7)
        self.motion_p4.setPageStep(1)
        self.motion_p4.setOrientation(QtCore.Qt.Vertical)
        self.motion_p4.setInvertedAppearance(False)
        self.motion_p4.setInvertedControls(False)
        self.motion_p4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p4.setTickInterval(1)
        self.motion_p4.setObjectName(_fromUtf8("motion_p4"))
        self.horizontalLayout_3.addWidget(self.motion_p4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 2, 1, 1)
        self.motion_p01 = QtGui.QSlider(self.horizontalLayoutWidget_4)
        self.motion_p01.setMinimum(0)
        self.motion_p01.setMaximum(65535)
        self.motion_p01.setPageStep(256)
        self.motion_p01.setOrientation(QtCore.Qt.Vertical)
        self.motion_p01.setInvertedAppearance(False)
        self.motion_p01.setInvertedControls(False)
        self.motion_p01.setTickPosition(QtGui.QSlider.TicksBelow)
        self.motion_p01.setTickInterval(1000)
        self.motion_p01.setObjectName(_fromUtf8("motion_p01"))
        self.gridLayout.addWidget(self.motion_p01, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.learn = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.learn.setObjectName(_fromUtf8("learn"))
        self.verticalLayout_2.addWidget(self.learn)
        self.detect = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.detect.setObjectName(_fromUtf8("detect"))
        self.verticalLayout_2.addWidget(self.detect)
        self.enable = QtGui.QCheckBox(self.horizontalLayoutWidget_4)
        self.enable.setObjectName(_fromUtf8("enable"))
        self.verticalLayout_2.addWidget(self.enable)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(MotionBox)
        QtCore.QMetaObject.connectSlotsByName(MotionBox)

    def retranslateUi(self, MotionBox):
        MotionBox.setWindowTitle(QtGui.QApplication.translate("MotionBox", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        MotionBox.setTitle(QtGui.QApplication.translate("MotionBox", "Motion detection", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MotionBox", "DETECT", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MotionBox", "VAR", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MotionBox", "MEM", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MotionBox", "IMG", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MotionBox", "DELTA", None, QtGui.QApplication.UnicodeUTF8))
        self.lock.setText(QtGui.QApplication.translate("MotionBox", "Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MotionBox", "vmax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MotionBox", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MotionBox", "vmin", None, QtGui.QApplication.UnicodeUTF8))
        self.learn.setText(QtGui.QApplication.translate("MotionBox", "learn", None, QtGui.QApplication.UnicodeUTF8))
        self.detect.setText(QtGui.QApplication.translate("MotionBox", "detect", None, QtGui.QApplication.UnicodeUTF8))
        self.enable.setText(QtGui.QApplication.translate("MotionBox", "enabled", None, QtGui.QApplication.UnicodeUTF8))

